### 계좌 생성 API
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 0
}

### 계좌 삭제 API
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002"
}