### 계좌 조회 API
GET http://localhost:8080/account?user_id=1
Content-Type: application/json

### 계좌 생성 API
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 1234500
}

### 계좌 삭제 API
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002"
}

