### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 10000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 10000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "355e1fdbfe934f07840f7e068f740c10",
  "accountNumber": "1000000000",
  "amount": 10000
}


### query transaction
GET http://localhost:8080/transaction/346ac262ffb0422288e370f3eb3c2cbe